server:
  port: 8762

spring:
  application:
    name: service-client
  zipkin:
    base-url: http://localhost:9411 #服务链追踪，web地址

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/